services:
  trim:
    image: trim:latest
    container_name: trim
    restart: unless-stopped
    networks:
      - containers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trim.rule=Host(`trim.mynetwork.net`)"
      - "traefik.http.routers.trim.tls=true"
      - "traefik.http.routers.trim.tls.certresolver=letsencrypt"
      - "traefik.http.services.trim.loadbalancer.server.port=80"

networks:
  containers:
    name: containers
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: br-containers