// ---------------------------------------------------------------------------
// Automated Calibration Pipeline — calibration asset registry (Stage 4).
//
// Maps each sliceable calibration step to the model it needs and resolves WHERE
// that model comes from, honoring the project's long-standing licensing stance:
// PerfectFit ships NO third-party calibration models. Sources, in priority:
//
//   1. user-provided file            — the user owns it; always allowed.
//   2. installed-slicer-resource     — the model shipped inside the user's own
//                                      Orca install (resources/calib/…); we
//                                      reference it, never redistribute it.
//   3. bundled                       — only assets whose license explicitly
//                                      permits redistribution (none ship today).
//   4. download                      — only when redistribution is permitted.
//   5. generated                     — Orca produces the geometry itself
//                                      (e.g. max volumetric speed); no file.
//
// A non-redistributable asset is NEVER served from a bundled/downloaded copy —
// only referenced from the user's own install or a file they supply.
//
// Pure module (no fs): resolution computes locations; the engine stage verifies
// the file exists and copies it. Gated behind the disabled flag.
// ---------------------------------------------------------------------------

import type { CalibrationId } from '../types';
import type { AssetLicenseMetadata, CalibrationAssetDefinition } from './types';

export type AssetSourceKind =
  | 'user-provided'
  | 'installed-slicer-resource'
  | 'bundled'
  | 'download'
  | 'generated';

const LICENSE_ORCA_RESOURCE: AssetLicenseMetadata = {
  license: 'AGPL-3.0 (part of the user\'s OrcaSlicer installation)',
  attribution: 'OrcaSlicer calibration models (SoftFever & contributors)',
  sourceUrl: 'https://github.com/SoftFever/OrcaSlicer',
  redistributable: false // referenced from the user's install, not shipped by us
};

const LICENSE_EXTERNAL_LINK: AssetLicenseMetadata = {
  license: 'See model page — not redistributed by PerfectFit',
  attribution: 'External community model (see MODEL_MANIFEST)',
  sourceUrl: null,
  redistributable: false
};

/**
 * The calibration asset registry. Only steps that can be automatically sliced
 * carry a model. Built-in Orca tests reference the user's install; steps that
 * need an external plate (shrinkage, final verification) stay link/user-provided;
 * max volumetric speed is generated by Orca with no model file.
 */
export const CALIBRATION_ASSETS: Partial<Record<CalibrationId, CalibrationAssetDefinition>> = {
  temperature: {
    id: 'orca-temp-tower',
    version: '2.4.x',
    displayName: 'Temperature tower',
    stepId: 'temperature',
    assetType: 'stl',
    slicerResourceRelPath: 'calib/temperature_tower/temperature_tower.stl',
    requiresParameterization: true, // per-height temperature changes injected
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['temperature'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  'flow-pass1': {
    id: 'orca-flow-pass1',
    version: '2.4.x',
    displayName: 'Flow ratio — coarse',
    stepId: 'flow-pass1',
    assetType: '3mf',
    slicerResourceRelPath: 'calib/filament_flow/flowrate-test-pass1.3mf',
    requiresParameterization: true, // per-block flow modifiers
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['flow-pass1'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  'flow-pass2': {
    id: 'orca-flow-pass2',
    version: '2.4.x',
    displayName: 'Flow ratio — fine',
    stepId: 'flow-pass2',
    assetType: '3mf',
    slicerResourceRelPath: 'calib/filament_flow/flowrate-test-pass2.3mf',
    requiresParameterization: true,
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['flow-pass2'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  'flow-verify': {
    id: 'orca-flow-verify',
    version: '2.4.x',
    displayName: 'Flow ratio — re-check (fine)',
    stepId: 'flow-verify',
    assetType: '3mf',
    slicerResourceRelPath: 'calib/filament_flow/flowrate-test-pass2.3mf',
    requiresParameterization: true,
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['flow-verify'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  'pressure-advance': {
    id: 'orca-pa-pattern',
    version: '2.4.x',
    displayName: 'Pressure advance pattern',
    stepId: 'pressure-advance',
    assetType: 'project-template', // complete project (embeds config + custom g-code)
    slicerResourceRelPath: 'calib/pressure_advance/pa_pattern.3mf',
    requiresParameterization: true,
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['pressure-advance'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  retraction: {
    id: 'orca-retraction-tower',
    version: '2.4.x',
    displayName: 'Retraction tower',
    stepId: 'retraction',
    assetType: 'stl',
    slicerResourceRelPath: 'calib/retraction/retraction_tower.stl',
    requiresParameterization: true,
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['retraction'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  'max-volumetric-speed': {
    id: 'orca-mvs-generated',
    version: '2.4.x',
    displayName: 'Max volumetric speed (generated by Orca)',
    stepId: 'max-volumetric-speed',
    assetType: 'generated', // Orca ramps flow parametrically; no model file ships
    requiresParameterization: true,
    license: LICENSE_ORCA_RESOURCE,
    compatibility: { stepIds: ['max-volumetric-speed'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  },
  shrinkage: {
    id: 'external-shrinkage-plate',
    version: '1',
    displayName: 'Shrinkage / dimensional plate (external)',
    stepId: 'shrinkage',
    assetType: 'stl',
    downloadUrl: 'https://www.printables.com/model/480907-shrinkage-calculator-dimensional-calibration-tool',
    requiresParameterization: false,
    license: {
      ...LICENSE_EXTERNAL_LINK,
      attribution: 'ap.engineering — Shrinkage Calculator / Dimensional Calibration Tool',
      sourceUrl: 'https://www.printables.com/model/480907-shrinkage-calculator-dimensional-calibration-tool'
    },
    compatibility: { stepIds: ['shrinkage'], nozzleDiametersMm: [0.4], requiredSlicerFeatures: [] }
  },
  'final-verification': {
    id: 'external-verification-model',
    version: '1',
    displayName: 'Final verification model (external, e.g. 3DBenchy)',
    stepId: 'final-verification',
    assetType: 'stl',
    downloadUrl: 'https://www.3dbenchy.com/download/',
    requiresParameterization: false,
    license: {
      license: 'CC BY-ND 4.0 — no redistribution',
      attribution: '#3DBenchy by Creative Tools',
      sourceUrl: 'https://www.3dbenchy.com/download/',
      redistributable: false
    },
    compatibility: { stepIds: ['final-verification'], nozzleDiametersMm: 'scalable', requiredSlicerFeatures: [] }
  }
};

export function getAsset(stepId: CalibrationId): CalibrationAssetDefinition | undefined {
  return CALIBRATION_ASSETS[stepId];
}

// --- resolution ------------------------------------------------------------

export interface AssetResolutionContext {
  /** The installed slicer's resource root, e.g. '…/OrcaSlicer/resources'. */
  slicerResourceRoot?: string;
  /** A file the user supplied for this step (always permitted). */
  userProvidedPath?: string;
  /** Whether downloading a redistributable asset is permitted right now. */
  allowDownload?: boolean;
}

export interface AssetResolution {
  available: boolean;
  stepId: CalibrationId;
  assetId: string | null;
  sourceKind: AssetSourceKind | null;
  /** Absolute path (bundled/installed/user) or URL (download), or null. */
  location: string | null;
  license: AssetLicenseMetadata | null;
  requiresParameterization: boolean;
  warnings: string[];
  /** What the user can do when nothing resolved. */
  remedy?: string;
}

/** Join a resource root and a relative path, matching the root's separator so
 *  the result is valid on the host OS (pure — no node 'path'). */
export function joinResourcePath(root: string, rel: string): string {
  const sep = root.includes('\\') && !root.includes('/') ? '\\' : root.includes('\\') ? '\\' : '/';
  const trimmedRoot = root.replace(/[\\/]+$/, '');
  const normalizedRel = rel.replace(/[\\/]+/g, sep);
  return `${trimmedRoot}${sep}${normalizedRel}`;
}

/**
 * Resolve where a step's calibration asset should come from. Never redistributes
 * a non-redistributable asset from a bundled/downloaded copy. Pure: does not
 * check the filesystem — the engine stage verifies existence at stage time.
 */
export function resolveAsset(stepId: CalibrationId, ctx: AssetResolutionContext = {}): AssetResolution {
  const def = CALIBRATION_ASSETS[stepId];
  if (!def) {
    return {
      available: false, stepId, assetId: null, sourceKind: null, location: null,
      license: null, requiresParameterization: false, warnings: [],
      remedy: 'No calibration asset is registered for this step.'
    };
  }
  const base = {
    stepId,
    assetId: def.id,
    license: def.license,
    requiresParameterization: def.requiresParameterization === true
  };

  // 1. User-provided always wins — the user owns the file.
  if (ctx.userProvidedPath) {
    return { ...base, available: true, sourceKind: 'user-provided', location: ctx.userProvidedPath, warnings: [] };
  }

  // 2. Generated by the slicer — no file needed.
  if (def.assetType === 'generated') {
    return { ...base, available: true, sourceKind: 'generated', location: null, warnings: [] };
  }

  // 3. The model shipped inside the user's own slicer install.
  if (def.slicerResourceRelPath && ctx.slicerResourceRoot) {
    return {
      ...base, available: true, sourceKind: 'installed-slicer-resource',
      location: joinResourcePath(ctx.slicerResourceRoot, def.slicerResourceRelPath), warnings: []
    };
  }

  // 4. Bundled — only if the license explicitly permits redistribution.
  if (def.bundledPath && def.license.redistributable) {
    return { ...base, available: true, sourceKind: 'bundled', location: def.bundledPath, warnings: [] };
  }

  // 5. Download — only a redistributable asset may be fetched automatically.
  if (def.downloadUrl && ctx.allowDownload && def.license.redistributable) {
    return { ...base, available: true, sourceKind: 'download', location: def.downloadUrl, warnings: [] };
  }

  // Nothing available: guide the user, honoring the no-redistribution rule.
  const remedy = def.downloadUrl
    ? `This model isn't redistributed by PerfectFit. Download it from ${def.downloadUrl} and select the file, or point PerfectFit at your OrcaSlicer installation.`
    : 'Select your OrcaSlicer installation so PerfectFit can use its calibration model, or supply the file yourself.';
  return {
    ...base, available: false, sourceKind: null, location: null,
    warnings: ['Calibration asset could not be resolved from an allowed source.'],
    remedy
  };
}
